name: Push
permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Login no Docker registry
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir a imagem Docker
        run: |
          ls
          cd urubu-do-pix-backend
          docker build -t "ghcr.io/LazaroJPR/Urubu-do-Pix-Backend:latest" -f Dockerfile .
          docker images
          docker push "ghcr.io/LazaroJPR/Urubu-do-Pix-Backend:latest"

      - name: Listar imagens
        run: docker images